
CREATE TABLE IF NOT EXISTS projetos_investimento (
    id_unico VARCHAR(255) PRIMARY KEY, 
    nome VARCHAR(500),
    cep VARCHAR(10),
    endereco VARCHAR(1000),
    descricao TEXT,
    funcao_social TEXT,
    meta_global TEXT,
    especie VARCHAR(100), 
    natureza VARCHAR(100),
    natureza_outras VARCHAR(100), 
    situacao VARCHAR(100), 
    desc_plano_nacional_politica_vinculado TEXT,
    uf CHAR(2),
    desc_populacao_beneficiada TEXT,
    observacoes_pertinentes TEXT,
    is_modelada_por_bim VARCHAR(5), 
    tomadores_nome VARCHAR(500),
    executores_nome VARCHAR(500),
    executores_codigo VARCHAR(255),
    repassadores_nome VARCHAR(500),
    eixos_descricao VARCHAR(500), 
    tipos_descricao VARCHAR(500),
    sub_tipos_descricao VARCHAR(500),
    fontes_de_recurso_origem VARCHAR(255), 
    
    data_inicial_prevista TIMESTAMP,
    data_final_prevista TIMESTAMP,
    data_inicial_efetiva TIMESTAMP,
    data_final_efetiva TIMESTAMP,
    data_cadastro TIMESTAMP,
    data_situacao TIMESTAMP,
    
    qdt_empregos_gerados INTEGER,
    populacao_beneficiada INTEGER,
    eixos_id INTEGER,
    tipos_id INTEGER,
    tipos_id_eixo INTEGER,
    sub_tipos_id INTEGER,
    sub_tipos_id_tipo INTEGER,
    
    tomadores_codigo NUMERIC(20, 2), 
    repassadores_codigo NUMERIC(20, 2), 
    fontes_de_recurso_valor_investimento_previsto NUMERIC(20, 2)
);